### ISSUE TITLE
Uploading/deleting files

### ISSUE THREAD

**Issue by omershk** [ProdPerfect/monday#11]
Hello, 

I was wondering if I can use change_item_value to upload and/or delete files from items in Monday (assuming that there's a files column in the board). If so, what arguments should be passed? any other changes required? 

Thank you!

**Comment by chdastolfo** [comment]
Hi!
Currently, the Monday API only supports clearing the file column. I can get to adding that capability here in the next week or so. Hopefully they allow us to upload files at some point in the near future.

**Comment by omershk** [comment]
Thank you

**Comment by chdastolfo** [comment]
Hi @omershk. I've added the method `add_file_to_column` to the items resource, which should allow you to upload files to items, given that you have a file column on the board. Because Monday's API requires the use a different endpoint to upload files, I couldn't just add functionality to the `change_item_value` method - I had to add this new one. Hopefully that works, but let me know if you have any issues using it.

As for deleting files, you can use the item methods to do that, although Monday's docs specify that if you want to clear file columns, you will need to pass {'clear_all': true} like in the following examples:

```
monday.items.change_item_value(board=1234512, item_id=122131, column='files', value={'clear_all': True})
monday.items.change_multiple_column_values(board=1234512, item_id=122131, column_values={'files': {'clear_all': True}})
```

Hope that helps!
