### ISSUE TITLE
Parse Error on 'monday.items.create_item()

### ISSUE THREAD

**Issue by CyberCityCircuits** [ProdPerfect/monday#14]
Our group names have '-' in them and this seems to cause a 'parse error' when I try to create an item with that group name.  I have tried several different delimindators ('\*, ^, \_, \[, \]) and they all seem to give different errors.  I really do need '-' in my group names. It does create the groups just fine though, it's only an issue when I try to create items. What can I do?

monday\_group = 'J2021-00016 - test999'

monday.items.create\_item(board=job\_board\_id, group=monday\_group.lower(),  item\_name='Do a thing')

{'errors': \[{'message': 'Parse error on "-00016" (FLOAT) at \[5, 28\]', 'locations': \[{'line': 5, 'column': 28}\]}\], 'account\_id': xxxxxxx}

**Comment by CyberCityCircuits** [comment]
This seems to work:  
    monday\_group = str(new\_number + ' - ' + job\_name)    create\_group\_return = monday.groups.create\_group(job\_board\_id, monday\_group)  
    group\_id = create\_group\_return\['data'\]\['create\_group'\]\['id'\]  
    monday.items.create\_item(board=job\_board\_id, group=group\_id,  item\_name='Do a thing')

**Comment by chdastolfo** [comment]
Hi! Sorry I missed this. I can make this clearer in the documentation because it is ambiguous - the create_item method is expecting the group_id (which is generated by Monday and won't have dashes in it), not the group name to be passed - which is the solution you came across, so I'm glad everything worked out! I'll update the docs so that's clearer.
