### ISSUE TITLE
In what manner does this package handle Monday API rate limits?

### ISSUE THREAD

**Issue by mvanaltvorst** [ProdPerfect/monday#44]
Hi, thank you for your effort maintaining this helpful package. However, I am wondering whether rate limits are being considered, and if not, how I can resolve my issues. Do you have experience with Monday rate limits?

**Comment by excellent-team** [comment]
hi @mvanaltvorst, I don't have experience with this package. More in general the monday enforced rate limits can be handles in either of these two ways. 

1. If the API returns "rate limit exhausted" post a non 200 back to monday so it will be retried. The problem here is burst mode as all retries will be done after the same delay. At the end you will bite your own tail and monday gives up on the request.
2. Try to prevent rate limits. My NodeJS based apps are using rabbitMQ to queue incoming request and drip them through to the API in a rate the API can handle. Monday.com does not handle burst mode very well.

**Comment by chdastolfo** [comment]
@excellent-team gives good advice. Monday rate limits are based on query complexity within a given period of time, and while this library has a method allowing you to check the complexity of your query, it does not "handle" Monday rate limits in any way. It's up to the developer to either prevent being rate limited or retry the request.
